### ISSUE TITLE
TypeError: main() missing 1 required positional argument: 'loop' when running via jira-oauth

### ISSUE THREAD

**Issue by rkadam** [rominf/jira-oauth#1]
Here are the steps I've taken.

* I've created virtual environment.
* Made sure I've starter_oauth.config in .oauthconfig folder.
* I installed this repo as a module
```
pip install .
```
* Upon executing jira-oauth, getting following error.
```
(roman-oauth-env) ➜  roman-oauth git:(master) jira-oauth
Traceback (most recent call last):
  File "/Users/rkadam/work/pywork/pyenvs/roman-oauth-env/bin/jira-oauth", line 11, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'loop'
```

**Comment by rominf** [comment]
@rkadam, thank you for the report. I fixed this in 0.1.10 which is already on PyPI.

In the future please use more descriptive issue title.
