### ISSUE TITLE
Problems with base URL's that has paths

### ISSUE THREAD

**Issue by goncalovalverde** [rominf/jira-oauth#5]
Whenever the base jira URL has a path the replacement leads to errors.
For example if the base URL is:
https://foo.bar/jira/ the "jira/" is ommited with you add the oauth path. This seems to be a problem with the yarl library and the .with_path 
The request_token_url ends up being:
https://foo.bar/plugins/servlet/oauth/request-token/ insted of https://foo.bar/jira/plugins/servlet/oauth/request-token/

(this happens also with the authorize_url)

**Comment by rominf** [comment]
Hi @goncalovalverde. I don't use Jira anymore. PR is welcome!

**Comment by goncalovalverde** [comment]
Hi. Thanks for your update.
I've added a quick fix. It's not pretty since it will include an extra "/" if the user includes it on the base path but it seems to work.
Already raised a PR
